require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
    - node_modules/**/*
  TargetRubyVersion: 2.7

################
# Style #
################
# %i が見にくいと思うので、配列記法に統一する
Style/SymbolArray:
  EnforcedStyle: brackets

# For rubocop < 1.0.0
Style/HashEachMethods:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformKeys:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformValues:
  Enabled: true

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# ドキュメントの無い class / module を許可する
Style/Documentation:
  Enabled: false

# クラス内のクラスなどの定義書式
# :: で繋ぐ書き方にする
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

# 空メソッドが 1 行だと見にくいので複数行にする
Style/EmptyMethod:
  EnforcedStyle: expanded

################
# Layout #
################
# コメントアウトは除外
# 80 は短すぎるので 100 まで許容する
Layout/LineLength:
  IgnoredPatterns: ['\A( *)#']
  Max: 100

################
# Metrics #
################
Metrics/BlockLength:
  Exclude:
    - config/environments/**/*

################
# Rails #
################
Rails/FilePath:
  EnforcedStyle: arguments
